server:
  port: 9060
spring:
  application:
    name: cart-service
  redis:
    host: 121.196.23.30
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5188/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN