server:
  port: 9188
spring:
  application:
    name: leyou-gateway
eureka:
    client:
      service-url:
        defaultZone: http://localhost:5188/eureka
    registry-fetch-interval-seconds: 5 # 每隔5秒拉去一次服务注册信息
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品服务的映射路径
    leyou-search: /search/** # 商品搜做服务
    user-service: /user/** # 商品搜做服务
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** # 授权中心微服务
  add-host-header: true # 携带头信息
  sensitive-headers: # 配置使用的头信息(PreDecorationFilter)
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
leyou:
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item